_format_version: "2.1"

services:
  - name: auth
    url: http://supabase-auth:9999
    routes:
      - name: auth-route
        paths:
          - /auth/v1
    plugins:
      - name: cors

  - name: rest
    url: http://supabase-rest:3000
    routes:
      - name: rest-route
        paths:
          - /rest/v1
    plugins:
      - name: cors

  - name: realtime
    url: http://supabase-realtime:4000
    routes:
      - name: realtime-route
        paths:
          - /realtime/v1
    plugins:
      - name: cors

  - name: storage
    url: http://supabase-storage:5000
    routes:
      - name: storage-route
        paths:
          - /storage/v1
    plugins:
      - name: cors
